"""removed dog name constaint

Revision ID: 0eb402224340
Revises: a35de7d969fb
Create Date: 2025-08-16 13:20:34.982295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb402224340'
down_revision = 'a35de7d969fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_index('ix_dog_name')
        batch_op.create_index(batch_op.f('ix_dog_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_name'))
        batch_op.create_index('ix_dog_name', ['name'], unique=1)

    # ### end Alembic commands ###
