"""dog attributes

Revision ID: 24bf4d0a9cbc
Revises: b65b7047e095
Create Date: 2024-04-30 16:00:10.535723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bf4d0a9cbc'
down_revision = 'b65b7047e095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20)))
        batch_op.add_column(sa.Column('emegergency_contact', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('feeding_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_needs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vet_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('vet_phone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('vet_phone')
        batch_op.drop_column('vet_name')
        batch_op.drop_column('special_needs')
        batch_op.drop_column('medications')
        batch_op.drop_column('feeding_instructions')
        batch_op.drop_column('emegergency_contact')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
