"""facility, users - more attributes added

Revision ID: 37acf0775e8b
Revises: 4f6064724f8b
Create Date: 2024-05-07 14:43:21.273414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37acf0775e8b'
down_revision = '4f6064724f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    with op.batch_alter_table('facility_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_and_qualifications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_owner', schema=None) as batch_op:
        batch_op.drop_column('skills_and_qualifications')
        batch_op.drop_column('about')

    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_column('about')
        batch_op.drop_column('services')

    # ### end Alembic commands ###
