"""facility attributes and registration

Revision ID: 4d04eb684aec
Revises: f2d9a88e6110
Create Date: 2024-04-24 21:00:08.453911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d04eb684aec'
down_revision = 'f2d9a88e6110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('services_offered', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('operating_hours', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pricing', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('capacity')
        batch_op.drop_column('pricing')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('operating_hours')
        batch_op.drop_column('amenities')
        batch_op.drop_column('services_offered')
        batch_op.drop_column('description')

    op.drop_table('facility_photo')
    # ### end Alembic commands ###
