"""facility longtude and latitude

Revision ID: 5533055d7820
Revises: 37875cfe5e89
Create Date: 2024-04-25 11:28:52.899498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5533055d7820'
down_revision = '37875cfe5e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
