"""dog size

Revision ID: a134dc8adf80
Revises: 5533055d7820
Create Date: 2024-04-25 16:09:42.958635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a134dc8adf80'
down_revision = '5533055d7820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = inspector.get_columns('dog')
    column_names = [column['name'] for column in columns]

    if 'size' not in column_names:
        with op.batch_alter_table('dog', schema=None) as batch_op:
            batch_op.add_column(sa.Column('size', sa.String(length=64), nullable=True))
            batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
            batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('image_file')
        batch_op.drop_column('weight')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
