"""booking services

Revision ID: b65b7047e095
Revises: bb71f320f57d
Create Date: 2024-04-29 23:40:35.466249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65b7047e095'
down_revision = 'bb71f320f57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daycare', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('boarding', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('boarding')
        batch_op.drop_column('daycare')

    # ### end Alembic commands ###
