"""users

Revision ID: c47d41d14482
Revises: f81b069e9b9b
Create Date: 2024-05-07 21:15:52.633000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47d41d14482'
down_revision = 'f81b069e9b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_owner', schema=None) as batch_op:
        batch_op.drop_column('about')
        batch_op.drop_column('skills_and_qualifications')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_and_qualifications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills_and_qualifications')
        batch_op.drop_column('about')

    with op.batch_alter_table('facility_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_and_qualifications', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('about', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
