"""facility, reviews

Revision ID: dc48e70fbfd0
Revises: c47d41d14482
Create Date: 2024-05-13 22:25:45.849754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc48e70fbfd0'
down_revision = 'c47d41d14482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_transport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_bookings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_column('completed_bookings')
        batch_op.drop_column('emergency_transport')

    op.drop_table('review')
    # ### end Alembic commands ###
